# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-26 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0003_auto_20161127_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosumableorder',
            name='consumable',
        ),
        migrations.RemoveField(
            model_name='cosumableorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='consumables',
        ),
        migrations.RemoveField(
            model_name='order',
            name='organization',
        ),
        migrations.DeleteModel(
            name='CosumableOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
