# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-26 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20161127_0315'),
        ('consumable', '0004_auto_20161127_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('consumables', models.ManyToManyField(to='consumable.Consumable')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderConsumables',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField()),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumable.Consumable')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumable.Order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
