# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-26 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0005_order_orderconsumables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='consumables',
        ),
        migrations.RemoveField(
            model_name='order',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='orderconsumables',
            name='consumable',
        ),
        migrations.RemoveField(
            model_name='orderconsumables',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderConsumables',
        ),
    ]
