# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-27 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0007_auto_20161127_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contacts',
            field=models.CharField(max_length=32, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=256, verbose_name='供应商名称'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='remark',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
    ]
