# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0008_auto_20161127_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumable',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='order',
            name='consumables',
        ),
        migrations.RemoveField(
            model_name='order',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='orderconsumables',
            name='consumable',
        ),
        migrations.RemoveField(
            model_name='orderconsumables',
            name='order',
        ),
        migrations.DeleteModel(
            name='Consumable',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderConsumables',
        ),
    ]
