# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-05 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_approve'),
        ('consumable', '0014_auto_20161204_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationRecord',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField()),
                ('number', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='picklist',
            name='status',
            field=models.IntegerField(choices=[(0, '通过'), (1, '未通过 '), (2, '审批中'), (3, '被驳回')], default=1),
        ),
    ]
