# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-06 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0015_auto_20161205_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='pick',
            name='can_return_number',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pick',
            name='return_number',
            field=models.IntegerField(default=0),
        ),
    ]
