# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-06 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumable', '0016_auto_20161206_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='OperationRecord',
        ),
    ]
