# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-06 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_approve'),
        ('consumable', '0017_auto_20161206_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationRecord',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField()),
                ('number', models.IntegerField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumable.Stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
