# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-15 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='base.Role', verbose_name='所属角色'),
        ),
    ]
