# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-18 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20161116_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.IntegerField(choices=[(1, '学校'), (2, '企业单位'), (3, '科研院所'), (4, '医院')], default=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Organization', verbose_name='所属机构'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ManyToManyField(to='base.Role', verbose_name='所属角色'),
        ),
    ]
