# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-20 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20161119_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='storagesites',
            name='remark',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='备注'),
        ),
    ]
