# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-21 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20161121_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='电话'),
        ),
    ]
