# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-26 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_role_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.IntegerField(choices=[(0, '系统管理员'), (1, '实验员'), (2, '采购员'), (3, '审批人'), (4, '库管员')], default=1),
        ),
    ]
