# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-04 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20161127_0315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, '系统管理员'), (1, '实验员'), (2, '采购员'), (3, '审批人'), (4, '库管员')], default=1),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
