# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-04 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20161205_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approve',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modify_time', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(0, '采购'), (1, '领用')])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Organization', verbose_name='所属机构')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
